version: '3'

#networks:
#  app-tier:
#    driver: bridge

services:
  timer-event:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
#    networks:
#      - app-tier
  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
#    networks:
#      - app-tier